import mongoose from "mongoose";

const TotalRevenueDistributionSchema = new mongoose.Schema({
  platformRevenue: {
    type: Number,
    required: true,
    min: 0,
    description:
      "Total earnings for the platform after TG owner percentages are deducted",
  },
  tgOwnerRevenue: {
    type: Number,
    required: true,
    min: 0,
    description: "Total revenue distributed to Telegram (TG) owners",
  },
  referrerEarnings: {
    type: Number,
    required: true,
    min: 0,
    description: "Total earnings generated by referrers",
  },
  createdAt: {
    type: Date,
    default: Date.now,
    description: "Timestamp when the revenue distribution record was created",
  },
});

export const TotalRevenueDistributionModel = mongoose.model(
  "TotalRevenueDistribution",
  TotalRevenueDistributionSchema
);
